npc:
  timed-refresh:
    mapping:
      group-dongjing-caiqi:
        operate-name: 攻击东京菜园
        start-position: 东京_菜园
        refresh-frequency: 180
        global-operation-objects:
          - 偷菜盗贼
          - 偷菜盗贼首领
        actions:
          - direction: LEFT
            repeat-times: 4
          - direction: UP
          - direction: RIGHT
          - direction: RIGHT
          - direction: DOWN
            has-callback: false
          - direction: DOWN
          - direction: LEFT

      group-mangrove:
        operate-name: 攻击柴家庄红树林
        start-position: 柴家庄
        refresh-frequency: 180
        global-operation-objects:
          - 红角巨兽
          - 成年红角巨兽
        actions:
          - direction: RIGHT
          - direction: RIGHT
            has-callback: false
          - direction: UP
          - direction: RIGHT
            repeat-times: 3
          - direction: DOWN
          - direction: LEFT
            repeat-times: 3
          - direction: DOWN
          - direction: RIGHT
            repeat-times: 3

      group-jingyanggang-woods:
        operate-name: 攻击景阳岗树林
        start-position: 景阳岗_树林
        refresh-frequency: 180
        global-operation-objects:
          - 景阳岗小大虫
          - 景阳岗大虫
        global-operation-steps:
          - 攻击景阳岗小大虫
          - 攻击景阳岗大虫
        actions:
          - direction: LEFT
            has-callback: false
            repeat-times: 2
          - direction: LEFT
          - direction: RIGHT
            repeat-times: 7
          - direction: UP
          - direction: LEFT