npc:
  timed-refresh:
    mapping:
      mangrove-boss1:
        operate-name: 攻击红角兽王
        start-position: 冰魄洞
        # 30 minutes
        refresh-frequency: 1800
        priority: 30
        global-operation-objects: 红角兽王
        actions:
          - direction: DOWN
            operation-steps: 攻击红角兽王

      mangrove-boss2:
        operate-name: 攻击红树林飞贼
        start-position: 柴家庄
        # 90 minutes
        refresh-frequency: 5400
        priority: 90
        global-operation-objects: 红树林飞贼
        actions:
          - direction: RIGHT
            has-callback: false
          - direction: RIGHT
            has-callback: false
          - direction: RIGHT
            has-callback: false
          - direction: DOWN
            has-callback: false
          - direction: DOWN
            operation-steps: 攻击红树林飞贼

      mangrove-boss3:
        operate-name: 攻击红树林飞贼头领
        start-position: 柴家庄
        # 120 minutes
        refresh-frequency: 7200
        priority: 120
        global-operation-objects: 红树林飞贼头领
        actions:
          - direction: RIGHT
            has-callback: false
          - direction: RIGHT
            has-callback: false
          - direction: RIGHT
            has-callback: false
          - direction: UP
            has-callback: false
          - direction: UP
            operation-steps: 攻击红树林飞贼头领

      huangnigang-boss1:
        operate-name: 攻击劫镖大当家
        start-position: 黄泥冈_小树林
        # 30 minutes
        refresh-frequency: 1800
        priority: 30
        global-operation-objects: 劫镖大当家
        actions:
          - direction: DOWN
            has-callback: false
          - direction: DOWN
            has-callback: false
          - direction: DOWN
            has-callback: false
          - direction: DOWN
            operation-steps: 攻击劫镖大当家

      huangnigang-boss2:
        operate-name: 攻击驾风神道
        start-position: 黄泥冈_小树林
        # 90 minutes
        refresh-frequency: 5400
        priority: 90
        global-operation-objects: 驾风神道
        actions:
          - direction: DOWN
            has-callback: false
          - direction: DOWN
            has-callback: false
          - direction: LEFT
            has-callback: false
          - direction: LEFT
            operation-steps: 攻击驾风神道

      huangnigang-boss3:
        operate-name: 攻击观景神僧
        start-position: 黄泥冈_小树林
        # 120 minutes
        refresh-frequency: 7200
        priority: 120
        global-operation-objects: 观景神僧
        actions:
          - direction: DOWN
            has-callback: false
          - direction: RIGHT
            has-callback: false
          - direction: RIGHT
            has-callback: false
          - direction: RIGHT
            operation-steps: 攻击观景神僧

      jingyanggang-boss1:
        operate-name: 攻击追风盗神
        start-position: 景阳岗_树林
        # 90 minutes
        refresh-frequency: 5400
        priority: 90
        global-operation-objects: 追风盗神
        actions:
          - direction: LEFT
            has-callback: false
          - direction: LEFT
            has-callback: false
          - direction: DOWN
            operation-steps: 攻击追风盗神

      jingyanggang-boss2:
        operate-name: 攻击摘星子
        start-position: 景阳岗_树林
        # 120 minutes
        refresh-frequency: 7200
        priority: 120
        global-operation-objects: 摘星子
        actions:
          - direction: RIGHT
            has-callback: false
          - direction: RIGHT
            has-callback: false
          - direction: RIGHT
            has-callback: false
          - direction: DOWN
            operation-steps: 攻击摘星子