server:
  port: 8080

spring:
  profiles:
    active: uat
    include:
      - config
      - npc-benefits
      - npc-fixed
      - npc-dungeon
      - npc-timed-refresh-50
      - npc-timed-refresh-80
      - npc-timed-refresh-100
      - npc-timed-refresh-120
      - npc-timed-refresh-boss