npc:
  timed-refresh:
    mapping:
      green-bamboo-forest:
        operate-name: 刷绿竹林
        start-position: 绿竹林
        refresh-frequency: 180
        enable-novice-protection: true
        global-operation-objects:
          - 蟒蛇
          - 大蟒蛇
        actions:
          - operation-steps:
              - 攻击蟒蛇
              - 攻击大蟒蛇
          - direction: RIGHT
            has-callback: false
          - direction: UP
            has-callback: false
          - direction: RIGHT
            has-callback: false
          - direction: UP
            operation-steps:
              - 攻击蟒蛇
              - 攻击大蟒蛇
          - direction: DOWN
            operation-steps:
              - 攻击蟒蛇
              - 攻击大蟒蛇
          - direction: LEFT
            operation-steps:
              - 攻击蟒蛇
              - 攻击大蟒蛇
          - direction: DOWN
            operation-steps:
              - 攻击蟒蛇
              - 攻击大蟒蛇
          - direction: RIGHT
            operation-steps:
              - 攻击蟒蛇
              - 攻击大蟒蛇
          - direction: LEFT
            has-callback: false
          - direction: DOWN
            operation-steps:
              - 攻击蟒蛇
              - 攻击大蟒蛇
          - direction: RIGHT
            operation-steps:
              - 攻击蟒蛇
              - 攻击大蟒蛇
          - direction: LEFT
            has-callback: false
          - direction: DOWN
            operation-steps:
              - 攻击蟒蛇
              - 攻击大蟒蛇
          - direction: RIGHT
            operation-steps:
              - 攻击蟒蛇
              - 攻击大蟒蛇

      dark-pool:
        operate-name: 刷幽暗池
        start-position: 幽暗池
        refresh-frequency: 180
        enable-novice-protection: true
        actions:
          - direction: DOWN
            operation-objects: 光电鱼
            operation-steps: 攻击光电鱼
          - direction: LEFT
            operation-objects: 光电鱼
            operation-steps: 攻击光电鱼
          - direction: DOWN
            operation-objects: 光电虾
            operation-steps: 攻击光电虾
          - direction: RIGHT
            operation-objects: 光电虾
            operation-steps: 攻击光电虾
          - direction: RIGHT
            operation-objects: 光电虾
            operation-steps: 攻击光电虾
          - direction: RIGHT
            operation-objects: 光电虾
            operation-steps: 攻击光电虾
          - direction: RIGHT
            operation-objects: 光电虾
            operation-steps: 攻击光电虾
          - direction: RIGHT
            operation-objects: 光电虾
            operation-steps: 攻击光电虾
          - direction: RIGHT
            operation-objects: 光电虾
            operation-steps: 攻击光电虾
          - direction: UP
            operation-objects: 光电鱼
            operation-steps: 攻击光电鱼
          - direction: LEFT
            operation-objects: 光电鱼
            operation-steps: 攻击光电鱼
          - direction: LEFT
            operation-objects: 光电鱼
            operation-steps: 攻击光电鱼
          - direction: LEFT
            operation-objects: 光电鱼
            operation-steps: 攻击光电鱼
          - direction: LEFT
            operation-objects: 光电鱼
            operation-steps: 攻击光电鱼
