npc:
  timed-refresh:
    mapping:
      group-green-bamboo-forest:
        operate-name: 攻击绿竹林
        start-position: 幽暗池
        refresh-frequency: 180
        enable-novice-protection: true
        global-operation-objects:
          - 蟒蛇
          - 大蟒蛇
        global-operation-steps:
          - 攻击蟒蛇
          - 攻击大蟒蛇
        actions:
          - direction: LEFT
          - direction: LEFT
          - direction: UP
          - direction: RIGHT
          - direction: LEFT
            has-callback: false
          - direction: UP
            has-callback: false
          - direction: LEFT
          - direction: RIGHT
          - direction: RIGHT
          - direction: LEFT
            has-callback: false
          - direction: UP
          - direction: RIGHT
          - direction: UP

      group-dark-pool:
        operate-name: 攻击幽暗池
        start-position: 幽暗池
        refresh-frequency: 180
        enable-novice-protection: true
        global-operation-objects:
          - 光电鱼
          - 光电虾
        global-operation-steps:
          - 攻击光电鱼
          - 攻击光电虾
        actions:
          - direction: DOWN
          - direction: LEFT
          - direction: DOWN
          - direction: RIGHT
            repeat-times: 6
          - direction: UP
          - direction: LEFT
            repeat-times: 4
