npc:
  benefits:
    mapping:
      benefits-open-today-spiritual-cultivation:
        operate-name: 开启今日修神
        start-position: 练武场
        global-operation-objects: 田武师
        actions:
          - operation-steps: 开启今日修神

      benefits-broken-dream-crystal:
        operate-name: 领取每日破碎梦晶石(151级)
        start-position: 史家庄
        actions:
          - direction: DOWN
            has-callback: false
          - direction: DOWN
            operation-objects: 史家丫鬟.小红
            operation-steps: 领取每日破碎梦晶石

      benefits-ancient-city-legend-map:
        operate-name: 领取每日古城传说图谱(151级)
        start-position: 桃花村
        actions:
          - operation-objects: 桃花村牧童
            operation-steps: 领取每日古城传说图谱

      benefits-platinum-vip:
        operate-name: 白金VIP每日福利
        actions:
          - operation-objects: 状态
            operation-steps:
              - 白金VIP
              - 领取奖励

      benefits-water-moon-mirror:
        operate-name: 领取水月镜(180级以上)
        start-position: 上梁山
        actions:
          - direction: UP
            has-callback: false
          - direction: UP
            operation-objects: 水月堂主
            operation-steps: 领取水月镜

      benefits-exchange-online-time:
        operate-name: 在线时间兑换
        start-position: 北大街
        global-operation-objects: 活动大使
        actions:
          - operation-steps: 在线时间x15兑换万虫羹x1
          - operation-steps: 在线时间x30兑换高级万虫羹x1
          - operation-steps: 在线时间x30兑换万虫羹x1(151级)
          - operation-steps: 在线时间x45兑换高级万虫羹x1(151级)
