spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hero_helper?useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    password: root
    username: root
# Mybatis Plus Config
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    call-setters-on-nulls: true